name: az_life
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/decisions.json
    - assets/json/school_questions.json
    - assets/json/university_exams.json
    - assets/json/relationship_events.json
    - assets/json/drama_events.json
    - assets/json/love_interactions.json
    - assets/json/restaurants.json
    - assets/json/wedding_config.json
    - assets/gameImages/
    - assets/sounds/
    - assets/personImages/
